# 应用名称
spring.application.name=bbs
# 应用服务 WEB 访问端口
server.port=8443
# 数据库驱动：
spring.datasource.driver-class-name = com.mysql.cj.jdbc.Driver
# 数据源名称
spring.datasource.name=defaultDataSource
# 数据库连接地址
spring.datasource.url=jdbc:mysql://110.40.159.129:3306/library?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
# 数据库用户名&密码：
spring.datasource.username=root
spring.datasource.password=
spring.servlet.multipart.max-file-size=30MB
spring.servlet.multipart.max-request-size=30MB
cos.baseUrl=project-1321048414.cos.ap-beijing.myqcloud.com
cos.accessKey=
cos.secretKey=
cos.regionName =ap-beijing
cos.bucketName=project-1321048414
cos.folderPrefix:/files
tencent.cos.bucketName=bucketname-1234567890
#redis
spring.redis.host=110.40.159.129
spring.redis.port=6379
spring.redis.password=root

